name: acme.sh Certificate
description: Use acme.sh to create SSL certificate
version: "1.001.1"
slug: "acme-sh-certificate"
init: false
homeassistant_api: true
arch:
  - aarch64
  - amd64
map:
  - type: ssl
    read_only: false
  - type: homeassistant_config
    read_only: false
options:
  email: ""
  config_sub_dicrectory: ""
  domains: null
schema:
  email: email
  config_sub_dicrectory: match(^[a-z][a-z0-9._]+$)
  domains:
    - domain: str
      issue_options: [str]
      deploy_options: [str]
      environment: [str]